namespace CustomerManagementSystem.Domain.Models;

// Response shape: a customer as read back from the DB. Every tbl_customers column except
// birthdate is NOT NULL, so Birthdate is the only optional member.
public sealed record CustomerModel
{
    public required Guid Guid { get; init; }

    public required string FirstName { get; init; }

    public required string LastName { get; init; }

    public required string Msisdn { get; init; }

    public required string Email { get; init; }

    public required CustomerStatus CustomerStatus { get; init; }

    // UTC.
    public required DateTime CreationDate { get; init; }

    // UTC.
    public required DateTime InteractionDate { get; init; }

    public required Gender Gender { get; init; }

    public DateOnly? Birthdate { get; init; }

    public required AddressModel Address { get; init; }
}

// Request shape for POST register. Deliberately all-nullable with no [Required], same
// reasoning as MerchantCredentials: CustomerRegistration validates every field itself, so a
// missing one gets this app's uniform 400 ResponseModel with a field-specific message.
// There's no Guid: a new customer's key is always generated by the DB.
public sealed class CreateCustomerRequest
{
    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public string? Msisdn { get; set; }

    public string? Email { get; set; }

    // Omitted = Gender.NotDeclared.
    public Gender? Gender { get; set; }

    public DateOnly? Birthdate { get; set; }

    // Omitted = Active. The only other value accepted is Test (the About page's bulk
    // generator) — see CustomerRegistration.
    public CustomerStatus? CustomerStatus { get; set; }

    public AddressRequest? Address { get; set; }
}

// Request shape for PATCH edit: a partial update, so every field but Guid is optional and an
// omitted one is left unchanged (usp_editCustomer's ISNULL(@param, column)). There's no
// CustomerStatus: edit is not a lifecycle transition (that's deactivate/reactivate/delete),
// so a status can't even be expressed here.
public sealed class UpdateCustomerRequest
{
    public Guid Guid { get; set; }

    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public string? Msisdn { get; set; }

    public string? Email { get; set; }

    public Gender? Gender { get; set; }

    public DateOnly? Birthdate { get; set; }

    public AddressRequest? Address { get; set; }
}

// The one key usp_getCustomer looks a customer up by — CustomerGetting fills exactly one
// member, chosen from the search term's shape.
public sealed record CustomerLookup(Guid? Guid = null, string? Msisdn = null, string? Email = null);
