namespace CustomerManagementSystem.Domain.Models;

public sealed record ProductModel
{
    public required Guid ProductId { get; init; }

    public required string Name { get; init; }

    public required string Category { get; init; }

    public string? Description { get; init; }

    public required decimal Price { get; init; }

    // Units originally stocked (never changes).
    public required int InitialQuantity { get; init; }

    // Units left on hand.
    public required int QuantityOnHand { get; init; }

    // Units sold: InitialQuantity - QuantityOnHand, derived in SQL rather than counted from
    // the purchase rows, so it stays consistent with QuantityOnHand even after a customer
    // (and their purchase rows) is deleted.
    public required int SoldQuantity { get; init; }

    // The warehouse the stock is held in.
    public required string Warehouse { get; init; }
}

// Request shape for POST product. Nullable strings with no [Required], same reasoning as
// CreateCustomerRequest — ProductCreation validates every field. No ProductId: a new product's
// key is always generated by the DB.
public sealed class CreateProductRequest
{
    public string? Name { get; set; }

    public string? Category { get; set; }

    public string? Description { get; set; }

    public decimal Price { get; set; }

    public int InitialQuantity { get; set; }

    public string? Warehouse { get; set; }
}
