namespace CustomerManagementSystem.Domain.Models;

public sealed record ProductModel
{
    public required Guid Guid { get; init; }

    public required string Name { get; init; }

    public required string Category { get; init; }

    public string? Comment { get; init; }

    public required decimal Price { get; init; }

    // Units originally stocked (never changes).
    public required int InventoryQuantity { get; init; }

    // Units left on hand.
    public required int StockQuantity { get; init; }

    // Units sold: InventoryQuantity - StockQuantity, derived in SQL rather than counted from
    // the purchase rows, so it stays consistent with StockQuantity even after a customer
    // (and their purchase rows) is deleted.
    public required int SoldQuantity { get; init; }

    // The depot (warehouse) the stock is held in.
    public required string Depot { get; init; }
}

// Request shape for POST product. Nullable strings with no [Required], same reasoning as
// CreateCustomerRequest — ProductRegistration validates every field. No Guid: a new product's
// key is always generated by the DB.
public sealed class CreateProductRequest
{
    public string? Name { get; set; }

    public string? Category { get; set; }

    public string? Comment { get; set; }

    public decimal Price { get; set; }

    public int InventoryQuantity { get; set; }

    public string? Depot { get; set; }
}
