<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <UserSecretsId>415eb2c0-23f1-45a3-9b40-4bb7ba047b26</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CustomerManagementSystem.BusinessLogic\CustomerManagementSystem.BusinessLogic.csproj" />
    </ItemGroup>

</Project>
