using CustomerManagementSystem.DataAccess.DBConnection;
using CustomerManagementSystem.Domain.Constants;
using CustomerManagementSystem.Domain.Models;

namespace CustomerManagementSystem.BusinessLogic.CustomerFunctions;

public class ProductCreation(IDbUtils dbUtils)
{
    // Product.Price is DECIMAL(12, 2) — the same money type as every amount in the three apps:
    // at most 10 integer digits and 2 decimals.
    private const decimal MaxPrice = 9_999_999_999.99m;

    // On success, Data is the new product's GUID — generated by the DB, like a customer's.
    public async Task<ResponseModel<Guid?>> CreateProductFunction(CreateProductRequest request,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.Name))
            return new ResponseModel<Guid?>(400, "Product name is required.");
        if (request.Name.Length > FieldLengthConstants.ProductName)
            return new ResponseModel<Guid?>(400, "Product name is too long.");

        if (string.IsNullOrWhiteSpace(request.Category))
            return new ResponseModel<Guid?>(400, "Category is required.");
        if (request.Category.Length > FieldLengthConstants.ProductCategory)
            return new ResponseModel<Guid?>(400, "Category is too long.");

        if (request.Description is not null && request.Description.Length > FieldLengthConstants.ProductDescription)
            return new ResponseModel<Guid?>(400, "Description is too long.");

        // Product's CK_Product_Price only requires >= 0; a strictly positive price
        // is a business rule for a newly listed product, not a DB-level constraint.
        if (request.Price <= 0)
            return new ResponseModel<Guid?>(400, "Price must be greater than zero.");

        // DECIMAL(12, 2): more than two decimals would be silently rounded by SQL Server, and
        // anything above MaxPrice overflows the column.
        if (decimal.Round(request.Price, 2) != request.Price || request.Price > MaxPrice)
            return new ResponseModel<Guid?>(400, $"Price must have at most two decimals and not exceed {MaxPrice:N2}.");

        if (request.InitialQuantity <= 0)
            return new ResponseModel<Guid?>(400, "Inventory quantity must be greater than zero.");

        if (string.IsNullOrWhiteSpace(request.Warehouse))
            return new ResponseModel<Guid?>(400, "Warehouse is required.");
        if (request.Warehouse.Length > FieldLengthConstants.ProductWarehouse)
            return new ResponseModel<Guid?>(400, "Warehouse is too long.");

        return await dbUtils.CreateProduct(request, cancellationToken);
    }
}
