using CustomerManagementSystem.DataAccess.DBConnection;
using CustomerManagementSystem.Domain.Constants;
using CustomerManagementSystem.Domain.Models;

namespace CustomerManagementSystem.BusinessLogic.CustomerFunctions;

public class ProductRegistration(IDbUtils dbUtils)
{
    // On success, Data is the new product's GUID — generated by the DB, like a customer's.
    public async Task<ResponseModel<Guid?>> RegisterProductFunction(CreateProductRequest request,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.Name))
            return new ResponseModel<Guid?>(400, "Product name is required.");
        if (request.Name.Length > FieldLengthConstants.ProductName)
            return new ResponseModel<Guid?>(400, "Product name is too long.");

        if (string.IsNullOrWhiteSpace(request.Category))
            return new ResponseModel<Guid?>(400, "Category is required.");
        if (request.Category.Length > FieldLengthConstants.ProductCategory)
            return new ResponseModel<Guid?>(400, "Category is too long.");

        if (request.Comment is not null && request.Comment.Length > FieldLengthConstants.ProductComment)
            return new ResponseModel<Guid?>(400, "Comment is too long.");

        // tbl_products' CK_tbl_products_price only requires >= 0; a strictly positive price
        // is a business rule for a newly listed product, not a DB-level constraint.
        if (request.Price <= 0)
            return new ResponseModel<Guid?>(400, "Price must be greater than zero.");

        // DECIMAL(10, 2): more than two decimals would be silently rounded by SQL Server, and
        // 10^8 or more overflows the column.
        if (decimal.Round(request.Price, 2) != request.Price || request.Price >= 100_000_000m)
            return new ResponseModel<Guid?>(400, "Price must have at most two decimals and be below 100,000,000.");

        if (request.InventoryQuantity <= 0)
            return new ResponseModel<Guid?>(400, "Inventory quantity must be greater than zero.");

        if (string.IsNullOrWhiteSpace(request.Depot))
            return new ResponseModel<Guid?>(400, "Depot is required.");
        if (request.Depot.Length > FieldLengthConstants.ProductDepot)
            return new ResponseModel<Guid?>(400, "Depot is too long.");

        return await dbUtils.CreateProduct(request, cancellationToken);
    }
}
